[package]
name = "counter"
version = "0.0.1"
edition = "2024.beta"

[dependencies]
MySo = { git = "https://github.com/The-Social-Proof-Foundation/myso-core.git", subdir = "crates/myso-framework/packages/myso-framework", rev = "framework/testnet" }

[addresses]
counter = "0x0"
