[package]
name = "move-bytecode-template"
description = "WASM variant of the move-binary-format which allows bytecode templates"
version = "0.1.1"
authors = ["Mysten Labs <build@socialprooflabs.com>"]
edition = "2021"
repository = "https://github.com/mystenlabs/myso.git"
license = "Apache-2.0"
publish = false

[dependencies]
hex = "0.4.3"
move-binary-format = { git = "https://github.com/MystenLabs/myso", features = ["wasm"] }
move-core-types = { git = "https://github.com/MystenLabs/myso", default-features = false}
serde = { version = "1.0.124", default-features = false }
serde-wasm-bindgen = "0.5.0"
serde_json = "1.0.64"
wasm-bindgen = "0.2.100"

[lib]
crate-type = ["cdylib"]
